### ISSUE TITLE
Update the "Find meeting time with another user" sample

### ISSUE THREAD

**Issue by PeppeDotNet** [pnp/copilot-prompts#25]
Hi team! 
The sample "[Find meeting time with another user](https://github.com/pnp/copilot-prompts/tree/main/samples/m365-time-finder-meeting-prompt)" is misleading because, by default, Copilot for Microsoft 365 can only look inside the current use agenda and not other people's agenda.
I suggest to change that prompt with this one:

`find the first 3 slots for a meeting with /[user1], /[user2] and /[user3]`

This prompt can work thanks to the plugin "Copilot for Meeting Slots": [https://copilotcircle.com/plugin/copilot-for-meetings](https://copilotcircle.com/plugin/copilot-for-meetings)

**Comment by rabwill** [comment]
Thanks @PeppeDotNet happy to update the sample. Keeping this issue open until it's update (as I am currently on vacation)

**Comment by PeppeDotNet** [comment]
Yes, the prompt is working with an external plugin

**Comment by rabwill** [comment]
Hi @PeppeDotNet at the moment this repo is exclusively prompts that work in first party apps.  You could still contribute the samples including the custom plugin if you'd like here - https://github.com/pnp/teams-dev-samples. Thanks for your time.

**Comment by rabwill** [comment]
Closing as this is out of scope.
