### ISSUE TITLE
Add the "Analyze my week" sample

### ISSUE THREAD

**Issue by PeppeDotNet** [pnp/copilot-prompts#27]
Hi Team,
I suggest to add the following prompt:

`look at my events in my calendar for this week and create categories that describe how I'm using my time. give me a brief description for each category and estimate the percentage of time I spend in each category`

**Comment by rabwill** [comment]
Awesome thanks @PeppeDotNet :) We will add this soon as a sample!

**Comment by rabwill** [comment]
Thank you @PeppeDotNet I have now added your sample. If you'd like to update any details in the read me pls feel free to raise a PR.
