### ISSUE TITLE
Prompt counter (Top contributors) does not show the actual number of prompts

### ISSUE THREAD

**Issue by AlexSweetPotato** [pnp/copilot-prompts#38]
Prompt counter (Top contributors) does not show the actual number of prompts. In the app shows 1 prompt but when you click over the contributor then you see that the actual number is 33 prompts.
<img width="295" alt="Issue Prompt Buddy 1" src="https://github.com/user-attachments/assets/761d49fc-76bd-48a8-99b7-12b4d56aceba">
<img width="272" alt="Issue Prompt Buddy 2" src="https://github.com/user-attachments/assets/c94aca74-b842-4529-9e3a-06ce63e3e9b2">

**Comment by rabwill** [comment]
Hi @AlexSweetPotato looks like you are referring to this Teams app built by the community [https://github.com/stuartridout/promptbuddy](https://github.com/stuartridout/promptbuddy) pls reach out to them in their repo. Our repo is for collecting prompts that work as is in Copilot.Thanks :)
