### ISSUE TITLE
Prompt Contribution | Copilot for Microsoft 365 | Meeting Minutes 

### ISSUE THREAD

**Issue by cswesh** [pnp/copilot-prompts#40]
I use this prompt to post any meeting in Copilot for Microsoft 365 chat to get the meeting minutes by referencing the saved meeting transcript. 

> Prompt
>
> Prepare a meeting minutes in a tabular format with following sections 
> "Meeting title" - get the title from the meeting invite , 
> "Attendees" - List all the name of the attendees who participated in the call, 
> "Meeting time" - Actual time of the meeting scheduled,
> "Meeting duration" - calculate the time in minutes of the actual time taken for the call, 
> "Discussion" - summarize the items discussed during the call and list the key insights,
> "Action items" - create a sub table with the following columns "no", "action items", "assigned to", "time frame"

Please let me know your thoughts

Thanks
Swesh

**Comment by rabwill** [comment]
Love it Swesh, would you be willing to add this as a sample like you did with the party planner :)

**Comment by cswesh** [comment]
Yes Rabia, would love to add them to the sameples

**Comment by rabwill** [comment]
Awesome, looking fwd to it :)
