### ISSUE TITLE
New Sample | M365 Meeting | Upcoming Meetings for the week with attendees

### ISSUE THREAD

**Issue by arjunumenon** [pnp/copilot-prompts#5]
I have created a prompt sample which list the upcoming meetings for this week. This prompt gives following details along with the meeting details.

- Date
- Time
- Meeting Details
- Initiated By
- List of Attendees
- RSVP Status

Here is the screenshot of the result

<img width="457" alt="image" src="https://github.com/pnp/copilot-prompts/assets/10369964/3fb2da3a-223a-4913-94b4-a74315d8cde7">

This sample has similarity with existing sample [m365-upcoming-meetings-prompt](https://github.com/pnp/copilot-prompts/tree/main/samples/m365-upcoming-meetings-prompt). 
If you think that the sample is a repetition, feel free to let me know so that this issue can be closed.

### Prompt Used

Here is the prompt which I have used for the result.

```
Show me my meetings for this week in table. Table should contain following details. Date, Time, Meeting Details, Initiated by, List of attendees, RSVP Status.
If RSVP Status is NOT Responded, show 🟠. If RSVP Status is Accepted, show 🟢.

If there are conflicts in my calendar for any events, show those events in bold
```

**Comment by rabwill** [comment]
Thanks @arjunumenon can you also put the prompt, I can only see the screenshot of the response.

**Comment by arjunumenon** [comment]
Apologies for not putting the prompt initially. I have updated the issue with the prompt used. I will initiate a new PR with this sample so that this could be merged if everything works as expected.
