### ISSUE TITLE
Add an explainer to the GitHub ReadME both explaining HOW to use these prompts and a guide for adding them

### ISSUE THREAD

**Issue by SimonDarksideJ** [pnp/copilot-prompts#6]
The site is great and to those who are fully versed in Copilot and its use, these prompts are extremely useful.

However, NOT everyone is.

Please add to the front page readme to this site:

* A simple description and links for where to learn more
* A quick-start guide on how to use these prompts
* A walk-through guide for how to add your own prompt (not just a template)

A Simple ask, and do the due-diligence to add documentation to a sample/store for Copilot prompts.

**Comment by rabwill** [comment]
Thanks @SimonDarksideJ for the suggestions, adding right away!

**Comment by rabwill** [comment]
Added contribution steps as well as resources to learn more.

**Comment by SimonDarksideJ** [comment]
> However for each sample prompt there is a readme on how to use them, this is suitably tailored for each prompt and cannot be generalised. Like using a prompt in PowerPoint may be different from the one used in Outlook etc.


The I'd suggest saying that also in the readme 😂

Thanks for listening, let's make it a great showcase.
