### ISSUE TITLE
Guest Users - missing data

### ISSUE THREAD

**Issue by CharlesSalvo** [pnp/copilot-prompts#71]
I'm working with a customer who has setup the solution (and they love it), the invited my external account and I can see the app - but see no data. I have been assigned a F3 license (which includes m365 power apps license). 

<img width="1349" alt="Screen Shot 2024-10-17 at 7 52 59 PM" src="https://github.com/user-attachments/assets/3463175b-b38d-4c67-a341-065844b40809">

**Comment by rabwill** [comment]
Hi @CharlesSalvo I think you have the wrong GitHub repo. I think what you are looking for is this repo to open your issueL: https://github.com/stuartridout/promptbuddy

**Comment by CharlesSalvo** [comment]
> Hi @CharlesSalvo I think you have the wrong GitHub repo. I think what you are looking for is this repo to open your issueL: https://github.com/stuartridout/promptbuddy

Your right, thank you!
