### ISSUE TITLE
Are these prompts Copilot-specific anymore?

### ISSUE THREAD

**Issue by mtomas7** [pnp/copilot-prompts#72]
In my view, AI models became so good, that I'm not sure that AI prompts are model-specific anymore. I think this community-based prompt library is great, but looking to the future, perhaps it could become a general library of curated prompts.

Another similar resource I use sometimes is Fabric Paterns: https://github.com/danielmiessler/fabric/tree/main/patterns

**Comment by rabwill** [comment]
Agree @mtomas7. Thanks for sharing the link. Since the PnP community is super Microsoft365 focused, we started it with Copilot, but you are right it will be even useful with any foundational AI models.
