### ISSUE TITLE
Issue with assigned categories when exporting prompts

### ISSUE THREAD

**Issue by AlexSweetPotato** [pnp/copilot-prompts#76]
We have created two new categories in Prompt Buddy. Performing an export test via JSON we have noticed that for prompts that have more than one category assigned, it only takes one of the assigned categories.
![image](https://github.com/user-attachments/assets/cf2c4ed9-8067-4a69-9ac4-74e63dd48f9a)

PS: We've checked the Prompt buddy deployed version 1.0.3.1 and latest 1.5.0.0
![image](https://github.com/user-attachments/assets/4ce01b36-bcd2-4eaa-90cf-a1012c8ed722)

**Comment by stuartridout** [comment]
Hi.  This is correct behaviour currently.   We are working on new export functionality to include different categories and export formats but we don't have a release schedule for this feature yet.

**Comment by AlexSweetPotato** [comment]
CONFIDENTIAL

Thanks Stuart,

Best regards.
________________________________

**Comment by rabwill** [comment]
Closing as this is not an issue for this repo ;) @stuartridout
